### ISSUE TITLE
GDAL for Cedar-14 stack should be built against libjpeg8, not libjpeg62

### ISSUE THREAD

**Issue by mjumbewu** [cyberdelia/heroku-geo-buildpack#22]
Thanks for maintaining this buildpack! I have gotten a lot of use out of it over the last year or so.

The new cedar-14 stack ships with libjpeg8, not libjpeg62 (see https://devcenter.heroku.com/articles/cedar-ubuntu-packages). But the GDAL downloaded by default for `heroku-geo-buildpack` appears to be compiled against libjpeg62. For a quick confirmation of this, you can run:

    git clone https://github.com/mjumbewu/super-simple-django-starter.git
    cd super-simple-django-starter
    git checkout geo
    heroku create
    heroku config:add BUILDPACK_URL=https://github.com/heroku/heroku-buildpack-multi.git
    git push heroku geo:master
    heroku run python app.py shell

Once you're in the shell, run:

```python
>>> from django.contrib.gis import gdal
```

You'll get a traceback to the tune of:

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 46, in <module>
        from django.contrib.gis.gdal.driver import Driver  # NOQA
      File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
        from django.contrib.gis.gdal.prototypes import ds as capi
      File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 8, in <module>
        from django.contrib.gis.gdal.libgdal import lgdal
      File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
        lgdal = CDLL(lib_path)
      File "/app/.heroku/python/lib/python2.7/ctypes/__init__.py", line 365, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libjpeg.so.62: cannot open shared object file: No such file or directory

**Comment by francisvierboom** [comment]
Just a quick note for anyone getting this error but for libjpeg.so.8 - I had a working app but strangely started getting this similar error just the other day. Fixed by [upgrading to cedar-14](https://devcenter.heroku.com/articles/cedar-14-migration).

```
heroku run "python manage.py check" 
...
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 8, in <module>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
    lgdal = CDLL(lib_path)
  File "/app/.heroku/python/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libjpeg.so.8: cannot open shared object file: No such file or directory
```

**Comment by cyberdelia** [comment]
Pin to the new version 1.3, this add support for stack, I've just forgot to tag it. This should fix it for everybody.

**Comment by tor29ben** [comment]
Hi,

I am sorry but the Tag still didn't help with the issue:
<code>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "/app/.heroku/python/lib/python3.4/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
    lgdal = CDLL(lib_path)
  File "/app/.heroku/python/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)</code>
