### ISSUE TITLE
Not working with Django? 

### ISSUE THREAD

**Issue by maroux** [cyberdelia/heroku-geo-buildpack#31]
Tried on both cedar and cedar-14, no luck :(

```→ cat .buildpacks 
https://github.com/cyberdelia/heroku-geo-buildpack.git#1.3
https://github.com/heroku/heroku-buildpack-python.git#v60
```

Deploy looks fine: 
```remote: =====> Downloading Buildpack: https://github.com/cyberdelia/heroku-geo-buildpack.git
remote: =====> Detected Framework: geos/gdal/proj
remote:        Using geos version: 3.4.2
remote:        Using gdal version: 1.11.1
remote:        Using proj version: 4.8.0_1
remote: -----> Vendoring geo libraries done
``` 

On running shell:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/__init__.py", line 46, in <module>
    from django.contrib.gis.gdal.driver import Driver  # NOQA
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as capi
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 8, in <module>
    from django.contrib.gis.gdal.libgdal import lgdal
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/gis/gdal/libgdal.py", line 48, in <module>
    lgdal = CDLL(lib_path)
  File "/app/.heroku/python/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /app/.heroku/vendor/lib: cannot read file data: Is a directory
```

In settings.py:
```
    GEOS_LIBRARY_PATH = os.environ.get('GEOS_LIBRARY_PATH')
    GDAL_LIBRARY_PATH = os.environ.get('GDAL_LIBRARY_PATH')
    PROJ4_LIBRARY_PATH = os.environ.get('PROJ4_LIBRARY_PATH')
--
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'
```

**Comment by ywarezk** [comment]
+1 getting the same thing

**Comment by pchiquet** [comment]
GeoDjango expects a file in `GEOS_LIBRARY_PATH`, `GDAL_LIBRARY_PATH ` and `PROJ4_LIBRARY_PATH ` settings, not a directory. (see the doc: https://docs.djangoproject.com/en/dev/ref/contrib/gis/install/geolibs/#geoslibrarypath)
 
So you should write the following lines in settings.py: 
  
    from os import environ
    GEOS_LIBRARY_PATH = "{}/libgeos_c.so".format(environ.get('GEOS_LIBRARY_PATH'))
    GDAL_LIBRARY_PATH = "{}/libgdal.so".format(environ.get('GDAL_LIBRARY_PATH'))
    PROJ4_LIBRARY_PATH = "{}/libproj.so".format(environ.get('PROJ4_LIBRARY_PATH'))

**Comment by aichaous** [comment]
i get the same error even if i added those lines to setting file

**Comment by aichaous** [comment]
maroux did you solve the problem
